### PR TITLE
Fix 404 Issue

### PR DESCRIPTION
**Pull request by JordanKnott**
Added code that catches 404 status codes when attempting to load content
then retrieves the 404 error page and loads that instead. Fixes issue
#148 where using the back button after visiting a 404 forces the user to
reload the page as only white content is shown.

### CODE REVIEW

**Comment by nicooprat** [comment]
Any plan to merge this PR? 💯

**Comment by Simon-Tang** [comment]
This looks great, but on the off-chance this PR gets looked at could you remove the whitespace changes so only the relevant lines are changed?

**Comment by JordanKnott** [comment]
@Simon-Tang If this PR gets any interaction from the repo owner, then definitely. As it stands, I don't think it ever will.

**Comment by luruke** [comment]
Thank you @JordanKnott and really sorry for the delay.

The new version will be using fetch API and also handle this kind of things.

**Pull request closed without merging**
